Create DjangoRepository class
veselij/ya_admin_panel pull request #18
Opened 2022-08-21 22:42 UTC by AmirbegKK

#7

2022-08-22 11:22 UTC, veselij requested changes

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +            tr_object = Transaction.objects.get(transaction.id)
можно место try except через get_or_create сделать

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +class Subscription(UUIDMixin, TimeStampedMixin):
у нас в фильмах лежит модель subscription, надо ее там расширить и сюда импортировать

2022-08-22 11:22 UTC, veselij commented on billing/services/repository.py
> +        raise NotImplementedError
а в чем смысл этого эксепшена? я его никогда не использовал, мне кажется наследования от Protocol достаточно

2022-08-22 11:22 UTC, veselij commented on billing/services/repository.py
> +        return django_models.User.objects.get(id=user_id).to_domain()
сделай плиз проверку на эксепшен DoesNotExist и если он происходит то рейзи кастомный эксепшен (надо его тоже написать) - типа ObjectDoesNotExist - я его в бизнес логике буду отлавливать и логировать и отправлять http ответ badrequest потом

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        indexes = [models.Index(fields=("price", "period_days"), name="subsription_idx")]
а зачем тут индекс?

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        indexes = [models.Index(fields=("price", "period_days"), name="transaction_idx")]
тут таких полей нет

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        db_table = "billing\".\"subscription"
имя не то, надо transction

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        verbose_name_plural = _("subscriptions")
тоже

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        tr_object.status = transaction.status
так не будет работать, там в transaction.user лежит модель User из service. а надо модель User из джанги. 
tr_object.user_id = transaction.user.id
или 
tr_object.user = User.objects.get_or_create(transaction.user.id)

2022-08-22 11:22 UTC, veselij commented on billing/models.py
> +        us_object.subscription = user_subscription.subscription
аналогично

2022-08-22 20:41 UTC, AmirbegKK commented on billing/services/repository.py
> +        raise NotImplementedError
В пеп по протоколам написано, что если мы явно наследуемся, то рекомендуется настоятельно этот эксепшн прописсывать. Делается это из-за того, что при наследовании мы можем через super() обратиться к методу родительского класса и тогда будет соответсвующая ошибка и мы поймем это. Иначе просто код отработает и все. Если бы мы от класса с протоколом не наследовались бы явно, то могли бы не прописывать его.

2022-08-22 20:46 UTC, AmirbegKK commented on billing/models.py
> +        indexes = [models.Index(fields=("price", "period_days"), name="subsription_idx")]
действительно, не нужен

2022-08-22 20:47 UTC, AmirbegKK commented on billing/services/repository.py
> +        raise NotImplementedError
К тому же так принято, раз класс абстрактный, то у него не должно быть реализации методов. Об этом и сообщаем таким образом

2022-08-22 20:51 UTC, AmirbegKK commented on billing/models.py
> +class Subscription(UUIDMixin, TimeStampedMixin):
Ты предлагаешь заменить этот Subscription тем что в movies? Мне кажется они должны быть разными

2022-08-22 20:55 UTC, AmirbegKK commented on billing/models.py
> +        tr_object.status = transaction.status
понял, спасибо

2022-08-22 21:38 UTC, veselij commented on billing/models.py
> +class Subscription(UUIDMixin, TimeStampedMixin):
нет, это одно и тоже. я его как раз добавлял в аус спринте. он дальше испольлзуется в аусе для фильтрации доступа. вот оставить его в app movies или тут я точно не знаю. но то, что должен быть один это факт

2022-08-22 21:39 UTC, veselij commented on billing/services/repository.py
> +        raise NotImplementedError
понял, спасибо!

2022-08-23 08:52 UTC, veselij commented on billing/models.py
> +        db_table = "billing\".\"subscription"
```suggestion
        db_table = "billing\".\"transaction"
```

2022-08-23 08:53 UTC, veselij approved these changes

2022-08-23 08:53 UTC, merged